### ISSUE TITLE
Can't get the tzxtap Python file working!

### ISSUE THREAD

**Issue by Alectronics** [shred/tzxtools#10]
I installed Python 3.8.8rct1 on my Windows 7 32bit computer and am able to run Python in the CMD screen as also in the IDLE 3.8.8. Python window. But none of the ZX Spectrum tools seem to work like the command lines tell!

Typing tzxtap -i Acehole.tzx -o Acehole.tap won't work giving an error.
And tzxtap.py -i Acehole.tzx -o Acehole.tap seems to work but gives no visible resulting file at all!

So I guess this doesn't work as the instruction guide presented. Because also >>>pip install txtools never works! and neither any of the other shown examples! To make sure the conversion TZX file was not the reason for failing i took an existing working file to try converting it to TAP format.
All invain!
So please explain why these tools never worked on my computer?!

**Comment by shred** [comment]
`pip install txtools` is the only way to install these tools, as pip will take care of creating the commands that invoke the Python scripts. Unfortunately you only say that pip "never works", but you don't give any more hints about what is actually happening if you invoke pip. It might be possible that you need to invoke `pip3 install tzxtools` if your system still has a mixed Python2/Python3 setup.

I invested a lot of my private time in developing these tools, but still publish them for free. I don't think I owe you an explanation. And to be honest, it is not very motivating if you berate me, instead of appreciating the fact that you got this tool for free, and find a constructive and respectful way to solve your problem.

**Comment by Alectronics** [comment]
I understand that you may have put a lot of work in this free tool. No argue about that, and no disrespect was intended! But it really never worked on my Python 3.3.8rc1 Windows7-32bit version. Not after many hours of testing, not as PIP, not as PIP3 or as any other example that was given. So that is why I replied with the problem that it simply failed and never worked in the as administrator opened CMD, and neither in the  IDLE Python 3.8.8.rc1 window either. Maybe it works in Windows 10 with a newer version. But sadly never on my Windows7 Python installed quad-core computer. And most of the time the given command line examples only resulted in syntax errors or nothing at all. Which is strange when it is supposed to be so easy as just typing a simple line of code according to online instructions.

**Comment by shred** [comment]
Fine for me.
