### ISSUE TITLE
Investigations (Graphtext 128 (UK))

### ISSUE THREAD

**Issue by spectrumcomputing** [shred/tzxtools#12]
Hi,

Thanks for providing these tools.  I'm trying to convert a game called Investigations which is available here:

https://spectrumcomputing.co.uk/entry/10833/ZX-Spectrum/Investigations

When I use tzxtap I get this error:

```
mint@mint:~/Downloads$ tzxtap Investigations.tzx
Error: Block 0 has no data content
```

I tried running tzxcleanup and got:

```
Noise blocks removed:        0
Blocks with CRC errors:      0
Blocks written:             27
```

Is there any way of fixing this?

Many thanks

**Comment by shred** [comment]
tap is a very limited file format compared to tzx. Whenever `tzxtap` cannot convert a tzx block to tap because it's not supported in the tap format, this error is reported. This way it avoids data loss and broken files that cannot be loaded later.

You can use the `--ignore` option here. If `tzxtap` discovers an unsupported block type, it will then just show a warning, and ignore that block.

You should also give an `-o` option for the tap output file name. In your case it would be:

```sh
tzxtap --ignore -o Investigations.tap Investigations.tzx
```

**Comment by shred** [comment]
I had a closer look at your file. The first block is just a comment block. It would not break the tap file if it is ignored, so `tzxtap` should not exit with an error here.

I will make `tzxtap` a bit more relaxed about blocks that can safely be ignored. Thank you for the report! :smile:

**Comment by spectrumcomputing** [comment]
Thanks @shred. Much appreciated.

**Comment by shred** [comment]
With the next release, `tzxtap` will just report a warning on comment blocks that can safely be ignored. The `--ignore` option will still be there for data blocks that cannot be converted, but if set, the resulting TAP file will likely be unloadable.
