### ISSUE TITLE
tzxls shows info about tzx ZX Spectrum tape images but not cdt Amstrad CPC ones

### ISSUE THREAD

**Issue by cpcbegin** [shred/tzxtools#4]
If I use this command in a tzx of a ZX Spectrum tape image show the right info but if I use it in an Amstrad CPC cdt image always show something like this:
```
$ tzxls /media/bobu/JBL4TB/emuladores/amstrad_cpc/cdt/antiriad_t2500.cdt 
  0  Hardware type               
  1  Pause                       2500 ms
  2  Turbo Speed Data Block      257 bytes of data, CRC ERROR!
  3  Turbo Speed Data Block      773 bytes of data, CRC ERROR!
  4  Turbo Speed Data Block      6967 bytes of data, CRC ERROR!
  5  Turbo Speed Data Block      31477 bytes of data, CRC ERROR!
```

**Comment by shred** [comment]
Yes, this is because the Amstrad CPC uses a different data format and a different CRC algorithm. tzxtools is unable to decode the data block contents. You can also ignore the CRC error, as it is only a bad CRC from a ZX Spectrum point of view.

You can still use tzxtools for many raw tzx operations and for extracting raw binary data. But I should have pointed out in the documentation that this toolset was mainly made for ZX Spectrum. Sorry...
